#!/usr/bin/env sh

unset GIT_LITERAL_PATHSPECS

PROJECT_DIR="$(git rev-parse --show-toplevel)"
LIBRARIES_FOLDER="libraries"
CORE_FILE="core"

emacs --batch -l "$PROJECT_DIR/$LIBRARIES_FOLDER/$CORE_FILE" \
      --eval "(byte-force-recompile \"$PROJECT_DIR/$LIBRARIES_FOLDER\")"
