#+STARTUP: entitiespretty nohideblocks

* My emacs config
** TODO Install Instructions

   To install:

    #+BEGIN_SRC shell
      git clone https://github.com/danilevy1212/emacsd ~/.emacs.d
    #+END_SRC

    If using ~emacs-version >= 27~ you can also install in the =$XDG_CONFIG_HOME= directory.

    #+BEGIN_SRC shell
      git clone https://github.com/danilevy1212/emacsd $XDG_CONFIG_HOME/emacs
    #+END_SRC

    Optionally, if using this configuration in multiple machines, you can enable
    my custom githooks, that recompile the "libraries" folder on each pull,
    making sure no stale byte-code will be loaded, by running:

    #+BEGIN_SRC shell
      git config core.hooksPath .githooks
    #+END_SRC

    or

    #+BEGIN_SRC shell
      find .git/hooks -type l -exec rm {} \;
      find .githooks -type f -exec ln -sf ../../{} .git/hooks/ \;
    #+END_SRC

** TODO Dependencies

   - Cmake :: For vterm
   - SSH needs to be setted up with Github and Gitlab accounts. :: For straight.el
   - mozc, mozc\under{}emacs\under{}helper :: For mozc.el
   - imagemagick :: For pdf-tools


** TODO Rationale

   Here I explained why my config is layed out the way it is.

*** Libraries

    1. utils
    2. completion
    3. system
    4. evil-plugins
    5. ui
    6. editor-conf
    7. rss
    8. org-lib
    9. pdf
    10. lsp
    11. elisp
    12. web (UNTESTED)
    13. python (UNTESTED)
    14. vim
    15. yaml
    16. json (UNTESTED)
    17. latex (UNTESTED)
    18. c/c++ (UNTESTED)
    19. haskell (UNTESTED)
    20. rust (UNTESTED)

** TODO Tips and Tricks

   Stuff I wish someone had to told me before I got serious with emacs. It may help people
   starting out with emacs.
